# Generated by Django 4.1.5 on 2023-06-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('isbn', models.BigIntegerField()),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=150)),
                ('discount_price', models.CharField(max_length=150)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='Book-photo/')),
                ('status', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
    ]
