# Generated by Django 4.2.2 on 2023-06-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Granthalaya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.BooleanField(blank=True, choices=[(1, 'Available'), (0, 'Unavailable')], default=0, null=True),
        ),
    ]
