# Generated by Django 4.1.5 on 2023-06-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Granthalaya', '0002_alter_book_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_title', models.CharField(max_length=100)),
                ('c_discription', models.CharField(max_length=250)),
            ],
        ),
    ]
